version: '3.1'

services:
    db:
      image: postgres:alpine
      restart: always
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: password123
      ports:
        - 5432:5432